### ISSUE TITLE
Do I need to install git on the host mac prior to applying this role?

### ISSUE THREAD

**Issue by yenarhee** [dirn/ansible-homebrew#1]
I get this error, when I try to run the playbook including the role:

TASK: [dirn.homebrew | Update] ***********************************************\* 
failed: [testmac05] => {"failed": true}
msg: You must: brew install git
Error: Failure while executing: git init

FATAL: all hosts have already failed -- aborting

I tried to install git explicitly but that doesn't work either.

roles:
    - role: dirn.homebrew
      homebrew_libraries:
        - git

I'm new to this and will be grateful for any help!

**Comment by dirn** [comment]
Yes, you do. [Git is a requirement for Homebrew](https://github.com/Homebrew/homebrew/blob/ea773061bbf18a42147b5b5a57005ccaae5e926d/share/doc/homebrew/Installation.md#requirements). It's installed as part of XCode's command line tools.

**Comment by yenarhee** [comment]
Thanks! Is there a way to install Xcode's command line tools with ansible as well?

**Comment by dirn** [comment]
The command line tools can be installed from the command line with

```
$ xcode-select --install
```

I don't see why you couldn't add that as a task in your playbook.

**Comment by yenarhee** [comment]
Thank you again! But I think the problem is that the mac I'm dealing with has an OS that's too old (10.6) and doesn't have Xcode-select. I guess I have to do it manually then or upgrade it...

**Comment by dirn** [comment]
Yes, Apple didn't add support for installing command line tools outside of Xcode until Lion (10.7). On older versions you'll need to install tools through Xcode.
