### ISSUE TITLE
Error running this role on RHEL 7

### ISSUE THREAD

**Issue by brainstorm** [dirn/ansible-homebrew#3]
Does this role assume that it's running on OSX and Ansible < 2.x?

```
Checking out files: 100% (1008/1008), done.
\n/home/brainstorm/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6:
 /home/brainstorm/.linuxbrew/Library/ENV/scm/git: No such file or directory\n
/home/brainstorm/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /home/brainstorm/.linuxbrew/Library/ENV/scm/git: No such file or directory\n/home/brainstorm/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /home/brainstorm/.linuxbrew/Library/ENV/scm/git: No such file or directory\n/home/brainstorm/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /home/brainstorm/.linuxbrew/Library/ENV/scm/git: No such file or directory\n/home/brainstorm/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /home/brainstorm/.linuxbrew/Library/ENV/scm/git: No such file or directory
```

```
98% (3803/3880)   \rChecking out files:  98% (3837/3880)   \rChecking out files:  99% (3842/3880)   \rChecking out files: 100% (3880/3880)   \rChecking out files: 100% (3880/3880), done.\nError: update-report should not be called directly!"
```

**Comment by dirn** [comment]
>Does this role assume that it's running on OSX

No. [It will use Homebrew on macOS and Linuxbrew on anything else](https://github.com/dirn/ansible-homebrew/blob/9fc509ce66834f999fb3a9cc93153225e323e751/tasks/main.yml#L6-L8).

>and Ansible < 2.x?

It doesn't assume that, but Ansible 2.0 hadn't been released yet the last time I made any changes to this role.

I haven't used this role in quite some time. There's a greater than 0 percent chance that stuff in either Linuxbrew or Ansible has changed enough that it no longer works. I'll happily accept pull requests to address that.

**Comment by brainstorm** [comment]
Sure thing ;)
